# Importation of data and preprocessing

# Question 1

In [1]:
import pandas as pd
import numpy as np

# Question 2

In [2]:
data=pd.read_csv('Documents/Cours Luxembourg 2025/banking.csv')
data=data.dropna()

In [15]:
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  object 
 2   marital         41188 non-null  object 
 3   education       41188 non-null  object 
 4   default         41188 non-null  object 
 5   housing         41188 non-null  object 
 6   loan            41188 non-null  object 
 7   contact         41188 non-null  object 
 8   month           41188 non-null  object 
 9   day_of_week     41188 non-null  object 
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  object 
 15  emp_var_rate    41188 non-null  float64
 16  cons_price_idx  41188 non-null  float64
 17  cons_conf_idx   41188 non-null 

# Question 3

In [3]:
data.head()

age          job  marital          education  default housing loan  \
0   44  blue-collar  married           basic.4y  unknown     yes   no   
1   53   technician  married            unknown       no      no   no   
2   28   management   single  university.degree       no     yes   no   
3   39     services  married        high.school       no      no   no   
4   55      retired  married           basic.4y       no     yes   no   

    contact month day_of_week  ...  campaign  pdays  previous     poutcome  \
0  cellular   aug         thu  ...         1    999         0  nonexistent   
1  cellular   nov         fri  ...         1    999         0  nonexistent   
2  cellular   jun         thu  ...         3      6         2      success   
3  cellular   apr         fri  ...         2    999         0  nonexistent   
4  cellular   aug         fri  ...         1      3         1      success   

  emp_var_rate  cons_price_idx  cons_conf_idx  euribor3m  nr_employed  y  
0          1.4          93.444          -36.1      4.963       5228.1  0  
1         -0.1          93.200          -42.0      4.021       5195.8  0  
2         -1.7          94.055          -39.8      0.729       4991.6  1  
3         -1.8          93.075          -47.1      1.405       5099.1  0  
4         -2.9          92.201          -31.4      0.869       5076.2  1  

[5 rows x 21 columns]

# Question 4

In [40]:
datanum=data.drop(['job','marital','education','default','housing','loan','contact','month','day_of_week','poutcome'], axis=1)
datanum

age  duration  campaign  pdays  previous  emp_var_rate  cons_price_idx  \
0       44       210         1    999         0           1.4          93.444   
1       53       138         1    999         0          -0.1          93.200   
2       28       339         3      6         2          -1.7          94.055   
3       39       185         2    999         0          -1.8          93.075   
4       55       137         1      3         1          -2.9          92.201   
...    ...       ...       ...    ...       ...           ...             ...   
41183   59       222         1    999         0           1.4          94.465   
41184   31       196         2    999         0           1.1          93.994   
41185   42        62         3    999         0           1.1          93.994   
41186   48       200         2    999         0          -3.4          92.431   
41187   25       112         4    999         0           1.1          93.994   

       cons_conf_idx  euribor3m  nr_employed  y  
0              -36.1      4.963       5228.1  0  
1              -42.0      4.021       5195.8  0  
2              -39.8      0.729       4991.6  1  
3              -47.1      1.405       5099.1  0  
4              -31.4      0.869       5076.2  1  
...              ...        ...          ... ..  
41183          -41.8      4.866       5228.1  0  
41184          -36.4      4.860       5191.0  0  
41185          -36.4      4.857       5191.0  0  
41186          -26.9      0.742       5017.5  0  
41187          -36.4      4.859       5191.0  0  

[41188 rows x 11 columns]

In [41]:
databis=data.iloc[:, np.array([0, 10,11,12,13, 15,16,17,18,19,20])]
databis

age  duration  campaign  pdays  previous  emp_var_rate  cons_price_idx  \
0       44       210         1    999         0           1.4          93.444   
1       53       138         1    999         0          -0.1          93.200   
2       28       339         3      6         2          -1.7          94.055   
3       39       185         2    999         0          -1.8          93.075   
4       55       137         1      3         1          -2.9          92.201   
...    ...       ...       ...    ...       ...           ...             ...   
41183   59       222         1    999         0           1.4          94.465   
41184   31       196         2    999         0           1.1          93.994   
41185   42        62         3    999         0           1.1          93.994   
41186   48       200         2    999         0          -3.4          92.431   
41187   25       112         4    999         0           1.1          93.994   

       cons_conf_idx  euribor3m  nr_employed  y  
0              -36.1      4.963       5228.1  0  
1              -42.0      4.021       5195.8  0  
2              -39.8      0.729       4991.6  1  
3              -47.1      1.405       5099.1  0  
4              -31.4      0.869       5076.2  1  
...              ...        ...          ... ..  
41183          -41.8      4.866       5228.1  0  
41184          -36.4      4.860       5191.0  0  
41185          -36.4      4.857       5191.0  0  
41186          -26.9      0.742       5017.5  0  
41187          -36.4      4.859       5191.0  0  

[41188 rows x 11 columns]

# 2  Logistic regression

# Question 1

In [42]:
from sklearn import linear_model
my_log = linear_model.LogisticRegression()

# Question 2

In [44]:
dataX=datanum.iloc[:,0:10]

dataY=datanum['y']

In [46]:
dataX

age  duration  campaign  pdays  previous  emp_var_rate  cons_price_idx  \
0       44       210         1    999         0           1.4          93.444   
1       53       138         1    999         0          -0.1          93.200   
2       28       339         3      6         2          -1.7          94.055   
3       39       185         2    999         0          -1.8          93.075   
4       55       137         1      3         1          -2.9          92.201   
...    ...       ...       ...    ...       ...           ...             ...   
41183   59       222         1    999         0           1.4          94.465   
41184   31       196         2    999         0           1.1          93.994   
41185   42        62         3    999         0           1.1          93.994   
41186   48       200         2    999         0          -3.4          92.431   
41187   25       112         4    999         0           1.1          93.994   

       cons_conf_idx  euribor3m  nr_employed  
0              -36.1      4.963       5228.1  
1              -42.0      4.021       5195.8  
2              -39.8      0.729       4991.6  
3              -47.1      1.405       5099.1  
4              -31.4      0.869       5076.2  
...              ...        ...          ...  
41183          -41.8      4.866       5228.1  
41184          -36.4      4.860       5191.0  
41185          -36.4      4.857       5191.0  
41186          -26.9      0.742       5017.5  
41187          -36.4      4.859       5191.0  

[41188 rows x 10 columns]

# Question 3

In [47]:
my_log.fit(dataX,dataY)
my_log.coef_


C:\Users\koudou5\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[ 0.00165983,  0.00454265, -0.00845957, -0.00159383, -0.03019586,
        -0.23631339,  0.30505001,  0.04474181, -0.26018224, -0.00550776]])

In [48]:
my_log.intercept_

array([0.00314867])

# Question 4

In [86]:
datapred=my_log.predict(dataX)
datapred

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [50]:
my_log.score(dataX, dataY)

0.9093182480334078

# 2.3.1 Hold out evaluation

# Question 1

In [87]:
from sklearn.model_selection import train_test_split

# Question 2

In [55]:
X_train, X_test, Y_train, Y_test = train_test_split(dataX, dataY, test_size=0.2)

In [56]:
X_train

age  duration  campaign  pdays  previous  emp_var_rate  cons_price_idx  \
7797    47       234         2    999         1          -1.8          92.893   
11436   54        65         3    999         0           1.1          93.994   
41172   27      1309         4    999         0           1.4          93.918   
36912   52       163         2    999         0           1.4          93.918   
38967   49       652         2    999         0           1.4          93.918   
...    ...       ...       ...    ...       ...           ...             ...   
10146   37       500         1    999         0           1.4          93.918   
16095   33       207         1    999         0          -1.8          93.075   
6934    48        66         1    999         0           1.4          93.444   
20172   46       173         1    999         0          -0.1          93.200   
19172   39       102        22    999         0           1.1          93.994   

       cons_conf_idx  euribor3m  nr_employed  
7797           -46.2      1.291       5099.1  
11436          -36.4      4.857       5191.0  
41172          -42.7      4.963       5228.1  
36912          -42.7      4.963       5228.1  
38967          -42.7      4.963       5228.1  
...              ...        ...          ...  
10146          -42.7      4.960       5228.1  
16095          -47.1      1.405       5099.1  
6934           -36.1      4.963       5228.1  
20172          -42.0      4.191       5195.8  
19172          -36.4      4.857       5191.0  

[32950 rows x 10 columns]

In [57]:
Y_train

7797     0
11436    0
41172    1
36912    0
38967    0
        ..
10146    0
16095    0
6934     0
20172    0
19172    0
Name: y, Length: 32950, dtype: int64

# Question 3 

Logistic regression

In [58]:
my_log.fit(X_train, Y_train)

C:\Users\koudou5\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [59]:
my_log.coef_



array([[ 0.00444641,  0.00452925, -0.07345848, -0.00158241,  0.01613239,
        -0.26171247,  0.1967173 ,  0.04213703, -0.27795478, -0.00354828]])

In [60]:
my_log.intercept_

array([0.00262249])

Perceptron

In [61]:
from sklearn.linear_model import Perceptron
ppn = Perceptron(max_iter=60, eta0=0.15, random_state=0)
ppn.fit(X_train, Y_train)

Perceptron(eta0=0.15, max_iter=60)

# Question 4

# Evaluation by accuracy

In [62]:
logregpred=my_log.predict(X_test)
logregpred

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [63]:
from sklearn.metrics import accuracy_score
# View model accuracy
# Defined as (1.0 - (# wrong predictions / # total observations))
print('Logistic regression Accuracy: %.2f' % accuracy_score(Y_test, logregpred))


Logistic regression Accuracy: 0.91


In [64]:
ppn_pred=ppn.predict(X_test)

In [65]:
print('Perceptron Accuracy: %.2f' % accuracy_score(Y_test, ppn_pred))

Perceptron Accuracy: 0.88


# Evaluation by F1-score

In [66]:
from sklearn.metrics import f1_score

In [67]:
print('my_log_f_1_score: %.2f' % f1_score(Y_test, logregpred))
print('ppn_f1_score: %.2f' % f1_score(Y_test, ppn_pred))

my_log_f_1_score: 0.51
ppn_f1_score: 0.02


# Confusion matrix 

In [68]:
from sklearn.metrics import confusion_matrix 

In [69]:
confusion_matrix_my_log = confusion_matrix(Y_test, logregpred)

In [70]:
print("Confusion matrix for the logistic regression model:", confusion_matrix_my_log, sep="\n")

Confusion matrix for the logistic regression model:
[[7087  191]
 [ 571  389]]


In [71]:
confusion_matrix_ppn = confusion_matrix(Y_test, ppn_pred)

In [72]:
print("confusion matrix for perceptron :", confusion_matrix_ppn, sep="\n")

confusion matrix for perceptron :
[[7272    6]
 [ 950   10]]


In [73]:
from sklearn.metrics import classification_report

In [53]:
print("classification report for the logistic regression model :", classification_report(Y_test, logregpred), sep="\n")
print("classification report for the perceptron model :", classification_report(Y_test, ppn_pred), sep="\n")

rapport pour le modèle de régression logistique :
              precision    recall  f1-score   support

           0       0.93      0.98      0.95      7334
           1       0.66      0.40      0.50       904

    accuracy                           0.91      8238
   macro avg       0.80      0.69      0.73      8238
weighted avg       0.90      0.91      0.90      8238

rapport pour le perceptron :
              precision    recall  f1-score   support

           0       0.96      0.84      0.90      7334
           1       0.36      0.73      0.48       904

    accuracy                           0.83      8238
   macro avg       0.66      0.79      0.69      8238
weighted avg       0.90      0.83      0.85      8238



# 2.3.2 Cross validation

# Question 1

In [74]:
from sklearn.model_selection import KFold

# Question 2
# Logistic Regression

In [76]:
kf10=KFold(n_splits=10, shuffle=False)
kf10.split(datanum)

<generator object _BaseKFold.split at 0x000001825DB51430>

# Questions 3 & 4

In [79]:
i = 1
somme=0
for train_index, test_index in kf10.split(datanum):
    X_train = datanum.iloc[train_index].iloc[:, 0:10]
    X_test = datanum.iloc[test_index].iloc[:,0:10]
    y_train = datanum.iloc[train_index].loc[:,'y']
    y_test = datanum.loc[test_index]['y']
        
    #Train the model
    my_log.fit(X_train, y_train) #Training the model
    print(f"Accuracy for the fold no. {i} on the test set: {accuracy_score(y_test, my_log.predict(X_test))}")
    somme = somme + accuracy_score(y_test, my_log.predict(X_test))
    i += 1
accuracy=somme/10
accuracy

C:\Users\koudou5\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy for the fold no. 1 on the test set: 0.9019179412478757
Accuracy for the fold no. 2 on the test set: 0.9106579266812334


C:\Users\koudou5\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy for the fold no. 3 on the test set: 0.9147851420247632


C:\Users\koudou5\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy for the fold no. 4 on the test set: 0.9075018208302986


C:\Users\koudou5\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy for the fold no. 5 on the test set: 0.9033746054867686
Accuracy for the fold no. 6 on the test set: 0.907016266084001


C:\Users\koudou5\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy for the fold no. 7 on the test set: 0.9072590434571498


C:\Users\koudou5\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy for the fold no. 8 on the test set: 0.9123573682932751


C:\Users\koudou5\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy for the fold no. 9 on the test set: 0.9118504128217582
Accuracy for the fold no. 10 on the test set: 0.9133074307916464


C:\Users\koudou5\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9090027957718771

# Other solution

In [80]:
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
# prepare the cross-validation procedure
cv = KFold(n_splits=10, shuffle=False)
# evaluate model
scores = cross_val_score(my_log, dataX, dataY, scoring='accuracy', cv=cv, n_jobs=-1)
# report performance
print('Logistic regression accuracy: %.5f (%.5f)' % (mean(scores), std(scores)))

Logistic regression accuracy: 0.90886 (0.00411)


In [81]:
Perceptron

sklearn.linear_model._perceptron.Perceptron

In [85]:
i = 1
somme=0
for train_index, test_index in kf10.split(datanum):
    X_train = datanum.iloc[train_index].iloc[:, 0:10]
    X_test = datanum.iloc[test_index].iloc[:,0:10]
    y_train = datanum.iloc[train_index].loc[:,'y']
    y_test = datanum.loc[test_index]['y']
        
    #Train the model
    ppn.fit(X_train, y_train) #Training the model
    print(f"Accuracy for the fold no. {i} on the test set: {accuracy_score(y_test, ppn.predict(X_test))}")
    somme = somme + accuracy_score(y_test, ppn.predict(X_test))
    i += 1
accuracy=somme/10
accuracy

Accuracy for the fold no. 1 on the test set: 0.8934207331876669
Accuracy for the fold no. 2 on the test set: 0.8897790725904345
Accuracy for the fold no. 3 on the test set: 0.9048312697256615
Accuracy for the fold no. 4 on the test set: 0.8880796309783928
Accuracy for the fold no. 5 on the test set: 0.8963340616654528
Accuracy for the fold no. 6 on the test set: 0.8997329448895363
Accuracy for the fold no. 7 on the test set: 0.9019179412478757
Accuracy for the fold no. 8 on the test set: 0.8999757222626851
Accuracy for the fold no. 9 on the test set: 0.8919378338999514
Accuracy for the fold no. 10 on the test set: 0.10684798445847499


0.8172857194906135

# second solution 

In [62]:

# evaluate model
scores = cross_val_score(ppn, dataX, dataY, scoring='accuracy', cv=cv, n_jobs=-1)
# report performance
print('Perceptron accuracy: %.5f (%.5f)' % (mean(scores), std(scores)))

Perceptron accuracy: 0.81729 (0.23687)


# with F1-score

In [82]:
scores = cross_val_score(my_log, dataX, dataY, scoring='f1', cv=cv, n_jobs=-1)
# report performance
print('Logistic regression F1 score: %.5f (%.5f)' % (mean(scores), std(scores)))

Logistic regression F1 score: 0.49012 (0.01996)


In [83]:
scores = cross_val_score(ppn, dataX, dataY, scoring='f1', cv=cv, n_jobs=-1)
# report performance
print('Perceptron F1 score: %.5f (%.5f)' % (mean(scores), std(scores)))

Perceptron F1 score: 0.26883 (0.16969)
